# frozen_string_literal: true

source "https://rubygems.org"

gem 'cucumber', '~> 6.1'
gem 'capybara', '3.35.3'
gem 'selenium-webdriver', '3.142.7'
gem 'rspec', '3.10'
gem 'faker', '2.18'
gem 'mongo', '2.14'