require "digest/md5"
require_relative "features/support/libs/mongo.rb"

def to_md5(pass)
  return Digest::MD5.hexdigest(pass)
end


task :test do
    puts "Testando rakefile"
end

task :seeds do
    users = [
        {name: "Gabriel", email: "gabriel_teste@gmail.com", password: to_md5("pwd123")},
      ]

      MongoDB.new.drop_danger
      MongoDB.new.insert_users(users)

      sh "cucumber"
end